


export const LAYER_GRAPHICS_TYPES_CONSTANTS = {
    NODES: "NODES",
    LINKS: "LINKS"
}

export const LAYER_TYPES_CONSTANTS = {
    FRONT: "FRONT",
    DATA: 'DATA',
    ANNOTATIONS: 'ANNOTATIONS',
    MAP: "MAP"
}