


export const LAYER_GRAPHICS_TYPES_CONSTANTS = {
    NODE_SHAPES: "NODES_SHAPES",
    NODE_LABELS: "NODE_LABELS",

    LINK_SHAPES: "LINK_SHAPES",
    LINK_LABELS: "LINK_LABELS"
}

export const LAYER_TYPES_CONSTANTS = {
    FRONT: "FRONT",
    DATA: 'DATA',
    ANNOTATIONS: 'ANNOTATIONS',
    MAP: "MAP"
}